export const RouteNames = {
  AuthRoutes: {
    LoginScreen: 'LoginScreen',
    OnBoardingScreen: 'OnBoardingScreen',
    SignUpScreen: 'SignUpScreen',
    ForgotPasswordScreen: 'ForgotPasswordScreen',
    ChangePasswrod: 'ChangePasswrod',
    OtpScreen: 'OtpScreen',
    SelectLanguage: 'SelectLanguage',
    GoogleSignUp: 'GoogleSignUp',
    SignIn: 'SignIn',
    VerifyUser: 'VerifyUser',
    ForgotPassVia: 'ForgotPassVia',
    ResetPassword: 'ResetPassword',
    PhoneSignin: 'PhoneSignin',
    RecoverPassword: 'RecoverPassword',
    WebViewScreen: 'WebViewScreen',
    ViewCertificate: 'ViewCertificate',
  },
  HomeRoutes: {
    DrawerStack: 'DrawerStack',
    TabStack: 'TabStack',
    HomeScreen: 'HomeScreen',
    NavigationScreen: 'NavigationScreen',
    Activity: 'Activity',
    ProfileScreen: 'ProfileScreen',
    EditProfileScreen: 'EditProfileScreen', 
    ChangePasswrod: 'ChangePasswrod',
    SubscriptionScreen: 'SubscriptionScreen',
    CourseDetails: 'CourseDetails',
    TransactionsHistory: 'TransactionsHistory',
    SettingScreen: 'SettingScreen',
    Search: 'Search',
    MyNotificationScreen: 'MyNotificationScreen',
    FavoriteCourseScreen: 'FavoriteCourseScreen',
    MyAccountScreen: 'MyAccountScreen',
    TransactionsDetails: 'TransactionsDetails',
    SupportAgent: 'SupportAgent',
    SupportAgentChat:'SupportAgentChat',
    PointAndAmountScreen: 'PointAndAmountScreen',
    ExchangeScreen: 'ExchangeScreen',
    PaymentScreen: 'PaymentScreen',
    RewardCoursesScreen: 'RewardCoursesScreen',
    MyWalletScreen: 'MyWalletScreen',
    Withdrawdetail: 'Withdrawdetail',
    InviteFriend: 'InviteFriend',
    InvitationRewards: 'InvitationRewards',
    ShareToChat: 'ShareToChat',
    WidthdrawAmountScreen: 'WidthdrawAmountScreen',
    AfterPurchaseCourseDetails: 'AfterPurchaseCourseDetails',
    CommonQuestions: 'CommonQuestions',
    BestPointsProgram: 'BestPointsProgram',
    AboutUsScreen: 'AboutUsScreen',
    AllCourseScreen: 'AllCourseScreen',
    VideoPlayerScreen: 'VideoPlayerScreen',
    QuestionChatFlow: 'QuestionChatFlow',
    WebViewScreen: 'WebViewScreen',
    ViewCertificate: 'ViewCertificate',
    CourseRating:'CourseRating',
    CourseStatusScreen:"CourseStatusScreen",
    WebViewPayment: 'WebViewPayment',
    PrivacyContentScreen: 'PrivacyContentScreen'
  },
};
